In [1]:
import numpy as np
rng = np.random.default_rng(seed=1701)  

x1 = rng.integers(10, size=6)  
x2 = rng.integers(10, size=(3, 4))  
x3 = rng.integers(10, size=(3, 4, 5))  

In [3]:
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)
print("dtype:   ", x3.dtype)

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60
dtype:    int64


In [5]:
x1

array([9, 4, 0, 3, 8, 6], dtype=int64)

In [7]:
x1[0]

9

In [9]:
x1[4]

8

In [11]:
x1[-1]

6

In [13]:
x1[-2]

8

In [15]:
x2

array([[3, 1, 3, 7],
       [4, 0, 2, 3],
       [0, 0, 6, 9]], dtype=int64)

In [17]:
x2[0,0]

3

In [19]:
x2[2,0]

0

In [21]:
x2[-2,-1]

3

In [23]:
x2[0,0]=12
x2

array([[12,  1,  3,  7],
       [ 4,  0,  2,  3],
       [ 0,  0,  6,  9]], dtype=int64)

In [25]:
x1[0]=3.14159
x1

array([3, 4, 0, 3, 8, 6], dtype=int64)

In [37]:
#slicing
x1

array([3, 4, 0, 3, 8, 6], dtype=int64)

In [31]:
x1[:3]

array([3, 4, 0], dtype=int64)

In [33]:
x1[3:]

array([3, 8, 6], dtype=int64)

In [35]:
x1[::2]

array([3, 0, 8], dtype=int64)

In [39]:
x1[1::2]

array([4, 3, 6], dtype=int64)

In [41]:
x1[::-1] 

array([6, 8, 3, 0, 4, 3], dtype=int64)

In [43]:
x1[4::-2]  

array([8, 0, 3], dtype=int64)

In [45]:
x2

array([[12,  1,  3,  7],
       [ 4,  0,  2,  3],
       [ 0,  0,  6,  9]], dtype=int64)

In [47]:
x2[:2, :3]

array([[12,  1,  3],
       [ 4,  0,  2]], dtype=int64)

In [49]:
x2[:3, ::2]

array([[12,  3],
       [ 4,  2],
       [ 0,  6]], dtype=int64)

In [51]:
x2[::-1, ::-1]

array([[ 9,  6,  0,  0],
       [ 3,  2,  0,  4],
       [ 7,  3,  1, 12]], dtype=int64)

In [53]:
x2[:, 0]

array([12,  4,  0], dtype=int64)

In [55]:
x2[0]

array([12,  1,  3,  7], dtype=int64)

In [57]:
print(x2)

[[12  1  3  7]
 [ 4  0  2  3]
 [ 0  0  6  9]]


In [59]:
x2_sub = x2[:2, :2]
print(x2_sub)


[[12  1]
 [ 4  0]]


In [61]:
x2_sub[0, 0] = 99
print(x2_sub)

[[99  1]
 [ 4  0]]


In [63]:
print(x2)

[[99  1  3  7]
 [ 4  0  2  3]
 [ 0  0  6  9]]


In [65]:
x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)

[[99  1]
 [ 4  0]]


In [67]:
x2_sub_copy[0, 0] = 42
print(x2_sub_copy)

[[42  1]
 [ 4  0]]


In [70]:
print(x2)

[[99  1  3  7]
 [ 4  0  2  3]
 [ 0  0  6  9]]


In [72]:
grid = np.arange(1, 10).reshape(3, 3)
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [74]:
x = np.array([1, 2, 3])
x.reshape((1, 3))

array([[1, 2, 3]])

In [76]:
x.reshape((3, 1))

array([[1],
       [2],
       [3]])

In [78]:

x[np.newaxis, :] 

array([[1, 2, 3]])

In [80]:
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

In [82]:
#concatenation
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])


array([1, 2, 3, 3, 2, 1])

In [84]:
z = np.array([99, 99, 99])
print(np.concatenate([x, y, z]))

[ 1  2  3  3  2  1 99 99 99]


In [86]:
grid = np.array([[1, 2, 3],
                 [4, 5, 6]])

In [88]:
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [90]:
np.concatenate([grid, grid], axis=1)


array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [92]:
#splitting
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]
